// <auto-generated />
using Frogobot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frogobot.Data.Migrations
{
    [DbContext(typeof(FrogoContext))]
    [Migration("20260314195122_UpdateGameModel")]
    partial class UpdateGameModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Frogobot.Data.Models.Game", b =>
                {
                    b.Property<uint>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowCustomLobbies")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BaseMaxPlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("MaxPlayersPerTeam")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("MaxTeamCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("ModdedMaxPlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsModsForMorePlayers")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Frogobot.Data.Models.User", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PossessPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscordUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Frogobot.Data.Models.UserGame", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("GameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscordUserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("Frogobot.Data.Models.UserGame", b =>
                {
                    b.HasOne("Frogobot.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frogobot.Data.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
